apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n6network-gw
spec:
  config: '{
    "cniVersion": "0.3.1",
      "name": "n6network-gw",
      "plugins": [
        {
          "type": {{ .Values.global.n6network.type | quote  }},
          "capabilities": { "ips": true },
          "master": {{ .Values.global.n6network.masterIf | quote }},
{{- if eq .Values.global.n6network.type "macvlan" }}
          "mode": "bridge",
{{- end }}
{{- if eq .Values.global.n6network.type "ipvlan" }}
          "mode": "l2",
{{- end }}
          "ipam": {
            "type": "static",
            "routes": [
             {
                  "dst": "10.1.0.0/16",
                  "gw": "10.100.100.12"
             },
             {
                  "dst": "10.61.0.0/16",
                  "gw": "10.100.100.12"
             }
            ]
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'