#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI, Ian Chen
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.packetrusher }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: packetrusher-configmap
  labels:
    app: {{ $.Values.projectName }}
    
data:
  config.yml: |

    gnodeb:
      controlif:
        ip: {{ .n2if.ipAddress | quote }}
        port: 9487
      dataif:
        ip: {{ .n3if.ipAddress | quote }}
        port: 2152
      plmnlist:
        mcc: "208"
        mnc: "93"
        tac: "000001"
        gnbid: "000008"
      slicesupportlist:
        sst: "01"
        sd: "010203" # optional, can be removed if not used

    ue:
      msin: "0000000001"
      key: "8baf473f2f8fd09487cccbd7097c6862"
      opc: "8e27b6af0e692e750f32667a3b14605d"
      amf: "8000"
      sqn: "00000000015b"
      dnn: "internet"
      routingindicator: "0000"
      hplmn:
        mcc: "208"
        mnc: "93"
      snssai:
        sst: 01
        sd: "010203" # optional, can be removed if not used
      integrity:
        nia0: false
        nia1: false
        nia2: true
        nia3: false
      ciphering:
        nea0: true
        nea1: false
        nea2: true
        nea3: false
    amfif:
      - ip: "10.100.50.193"
        port: 38412
      - ip: "10.100.50.194"
        port: 38412
      - ip: "10.100.50.195"
        port: 38412
      - ip: "10.100.50.196"
        port: 38412
      - ip: "10.100.50.197"
        port: 38412
      - ip: "10.100.50.198"
        port: 38412
      - ip: "10.100.50.199"
        port: 38412
      - ip: "10.100.50.200"
        port: 38412
      - ip: "10.100.50.201"
        port: 38412
      - ip: "10.100.50.202"
        port: 38412
      - ip: "10.100.50.203"
        port: 38412
      - ip: "10.100.50.204"
        port: 38412

    logs:
        level: 7

    test:
      printTimeStamp: false
      periodicPDUSessionCreateDestroy: true
    
{{- end }}

