#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.packetrusher }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ $.Values.projectName }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.projectName }}
  template:
    metadata:
      labels:
        app: {{ $.Values.projectName }}
      annotations:
        {{- if or $.Values.global.n2network.enabled $.Values.global.n3network.enabled}}
        k8s.v1.cni.cncf.io/networks: '[
        {{- if $.Values.global.n2network.enabled }}
            { "name": "{{ $.Values.global.n2network.name }}",
              "interface": "n2",
              "ips": [ "{{ .n2if.ipAddress }}/{{ $.Values.global.n2network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n2network.gatewayIP }}" ]
            },
        {{- end }}
            { "name": "{{ $.Values.global.n3network.name }}",
              "interface": "n3",
              "ips": [ "{{ .n3if.ipAddress }}/{{ $.Values.global.n3network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n3network.gatewayIP }}" ]
            }
            ]'
        {{- end }}
    spec:
      initContainers:
      - name: wait-amf
        {{- with $.Values.initcontainers.sctp_test }}
        image: {{ .image.name }}:{{ .image.tag }}
        imagePullPolicy: {{ .image.pullPolicy }}
        {{- end }}
        command: ["sh", "-c", "until sctp_test -s -H 0.0.0.0 -P 25000 -h {{ .amf.n2if.ipAddress }} -p {{ .amf.n2if.port }}; do echo waiting for the AMF; sleep 2; done;"]
      containers:
      - name: packetrusher
        image: towards5gs/packetrusher
        imagePullPolicy: {{ .image.pullPolicy }}
        env:
        - name: NGAP_LOCAL_ADDR
          value: "10.100.50.250"
        - name:  GTPU_LOCAL_ADDR
          value: "10.100.50.236"
        - name: NGAP_REMOTE_ADDR
          value: "10.100.50.249"
        - name: MCC
          value: "208"
        - name: MNC
          value: "93"
        - name:  TAC
          value: "000001"
        - name: GNBID
          value: "000008"
        - name: SST_GNB
          value: "01"
        - name: SD
          value: "010203"
        - name: MSIN
          value:  "0000000003"
        - name: KEY
          value: "8baf473f2f8fd09487cccbd7097c6862"
        - name: OPC
          value: "8e27b6af0e692e750f32667a3b14605d"
        - name: DNN
          value: "internet"
        - name: SST_UE
          value: "01"
        - name: NUM_UE
          value: "100"

{{- end }}
{{- end }}
        