apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-macvlan-deployment
  labels:
    app: gw-macvlan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw-macvlan
  template:
    metadata:
      labels:
        app: gw-macvlan
      annotations:
      {{- with .Values.global }}
        k8s.v1.cni.cncf.io/networks: '[ 
                                        { 
                                          "name": "n6network-gw", 
                                          "interface": "n6", 
                                          "ips": [ 
                                                "{{ .n6If.ipAddress }}/{{ .n6network.cidr }}" 
                                              ] 
                                        } 
                                      ]'
      {{- end }}
    spec:
      containers:
      - name: gw-macvlan
        image: networkstatic/iperf3
        securityContext:
          privileged: true
        command: [ "/bin/sh", "-c" ]
        args: [ "apt update; apt -y install iproute2 procps iptables; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; sysctl -w net.ipv4.ip_forward=1; sleep infinity;" ]
