#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI, Ian Chen
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.chf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-chf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
data:
  chfcfg.yaml: |

    info:
      version: 1.0.3
      description: CHF initial local configuration

    configuration:
      chfName: CHF # the name of this CHF
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: {{ include "free5gc-chf.fullname" $ }}-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0 # IP used to bind the service
        port: {{ .services.chf.port }} # port used to bind the service
        tls: # the local path of TLS key
          pem: ../cert/chf.pem # CHF TLS Certificate
          key: ../cert/chf.key # CHF TLS Private key
      nrfUri: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}  # a valid URI of NRF
      nrfCertPem: ../cert/nrf.pem # NRF Certificate
      serviceNameList: # the SBI services provided by this CHF, refer to TS 32.291
        - nchf-convergedcharging # Nchf_AMPolicyControl service
      mongodb: # the mongodb connected by this CHF
        name: free5gc # name of the mongodb
        url: mongodb://{{ $.Values.mongodb.service.name }}:{{ $.Values.mongodb.service.port }} # a valid URL of the mongodb
      quotaValidityTime: 10000
      volumeLimit: 50000
      volumeLimitPDU: 10000
      volumeThresholdRate: 0.8
      cgf:
        hostIPv4: {{ $.Values.global.webui.service.name }}
        port: {{ $.Values.global.webui.service.port }}
        listenPort: {{ $.Values.global.cgf.service.port }}
        tls:
          pem: ../cert/chf.pem
          key: ../cert/chf.key
        cdrFilePath: /tmp
      abmfDiameter:
        protocol: tcp
        hostIPv4: 0.0.0.0
        port: 3868
        tls:
          pem: ../cert/chf.pem
          key: ../cert/chf.key
      rfDiameter:
        protocol: tcp
        hostIPv4: 0.0.0.0
        port: 3869
        tls:
          pem: ../cert/chf.pem # CHF TLS Certificate
          key: ../cert/chf.key # CHF TLS Private key
    logger: # log output setting
      enable: true # true or false
      level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or false

{{- end }}
