#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI, Ian Chen
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.amf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-amf.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
    
data:
  amfcfg.yaml: |

    info:
      version: 1.0.9
      description: AMF initial local configuration
    
    configuration:
      amfName: {{ $.Values.global.amf.amfName }}
      ngapIpList:
        {{- if $.Values.global.amf.service.ngap.enabled }}
          - 0.0.0.0
        {{- else }}
        - {{ $.Values.global.amf.n2if.ipAddress }}
        {{- end }}
      ngapPort: {{ $.Values.global.amf.service.ngap.port }} # the SCTP port listened by NGAP
      sbi:
        scheme: {{ $.Values.global.sbi.scheme }}
        registerIPv4: {{ include "free5gc-amf.fullname" $ }}-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ .service.port }}
        tls:
          key: ../cert/amf.key
          pem: ../cert/amf.pem
      serviceNameList:
        - namf-comm # Namf_Communication service
        - namf-evts # Namf_EventExposure service
        - namf-mt   # Namf_MT service
        - namf-loc  # Namf_Location service
        - namf-oam  # OAM service
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      backupAmfName: AMF2
      supportTaiList:  # the TAI (Tracking Area Identifier) list supported by this AMF
        - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          tac: 000001 # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
      plmnSupportList: # the PLMNs (Public land mobile network) list supported by this AMF
        - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          snssaiList: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
            - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      supportDnnList:  # the DNN (Data Network Name) list supported by this AMF
        - internet
      nrfUri: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}
      nrfCertPem: ../cert/nrf.pem # NRF Certificate
      security:  # NAS security parameters
        integrityOrder: # the priority of integrity algorithms
          - NIA2
          # - NIA0
        cipheringOrder: # the priority of ciphering algorithms
          - NEA0
          - NEA2
      networkName:  # the name of this core network
        full: free5GC
        short: free
      ngapIE: # Optional NGAP IEs
        mobilityRestrictionList: # Mobility Restriction List IE, refer to TS 38.413
          enable: true # append this IE in related message or not
        maskedIMEISV: # Masked IMEISV IE, refer to TS 38.413
          enable: true # append this IE in related message or not
        redirectionVoiceFallback: # Redirection Voice Fallback IE, refer to TS 38.413
          enable: false # append this IE in related message or not
      nasIE: # Optional NAS IEs
        networkFeatureSupport5GS: # 5gs Network Feature Support IE, refer to TS 24.501
          enable: true # append this IE in Registration accept or not
          length: 1 # IE content length (uinteger, range: 1~3)
          imsVoPS: 0 # IMS voice over PS session indicator (uinteger, range: 0~1)
          emc: 0 # Emergency service support indicator for 3GPP access (uinteger, range: 0~3)
          emf: 0 # Emergency service fallback indicator for 3GPP access (uinteger, range: 0~3)
          iwkN26: 0 # Interworking without N26 interface indicator (uinteger, range: 0~1)
          mpsi: 0 # MPS indicator (uinteger, range: 0~1)
          emcN3: 0 # Emergency service support indicator for Non-3GPP access (uinteger, range: 0~1)
          mcsi: 0 # MCS indicator (uinteger, range: 0~1)
      t3502Value: 720  # timer value (seconds) at UE side
      t3512Value: 3600 # timer value (seconds) at UE side
      non3gppDeregTimerValue: 3240 # timer value (seconds) at UE side
      # retransmission timer for paging message
      t3513:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Deregistration Request message
      t3522:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Registration Accept message
      t3550:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Configuration Update Command message
      t3555:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Authentication Request/Security Mode Command message
      t3560:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Notification message
      t3565:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Identity Request message
      t3570:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      locality: area1 # Name of the location where a set of AMF, SMF, PCF and UPFs are located
      sctp: # set the sctp server setting <optinal>, once this field is set, please also add maxInputStream, maxOsStream, maxAttempts, maxInitTimeOut
        numOstreams: 3 # the maximum out streams of each sctp connection
        maxInstreams: 5 # the maximum in streams of each sctp connection
        maxAttempts: 2 # the maximum attempts of each sctp connection
        maxInitTimeout: 2 # the maximum init timeout of each sctp connection
      defaultUECtxReq: false # the default value of UE Context Request to decide when triggering Initial Context Setup procedure

    logger:
      enable: true # true or false
      level: trace # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or false

{{- end }}

